/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.vo.Coches;
import modelo.vo.Empleados;

/**
 *
 * @author AD
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        controladorPrincipal.iniciaSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogCliente = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodCli = new javax.swing.JTextField();
        txtNomCli = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTfno = new javax.swing.JTextField();
        btnAltaCli = new javax.swing.JButton();
        btnBajaCli = new javax.swing.JButton();
        btnModifCli = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        DialogCoche = new javax.swing.JDialog();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();
        btnInsertCoche = new javax.swing.JButton();
        btnBajaCoche = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        DialogReparaciones = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRepMatricula = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtRepFechaEnt = new javax.swing.JTextField();
        txtRepFechaSal = new javax.swing.JTextField();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        cbEmpleados = new javax.swing.JComboBox<>();
        btnComprobar = new javax.swing.JButton();
        DialogTablaCoches = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCoches = new javax.swing.JTable();
        DialogTablaBonificacionEmpleados = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        cbMesEmpleados = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        DialogTablaFacturacion = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFacturacion = new javax.swing.JTable();
        cbMesFacturacion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        DialogTablaClienteCochesReparaciones = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        txtNombreTablaClientes = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNumCoches = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaReparacionesCoche = new javax.swing.JTable();
        btnBuscarClienteCoches = new javax.swing.JButton();
        btnDialogCliente = new javax.swing.JButton();
        btnDialogCoches = new javax.swing.JButton();
        btnDialogReparaciones = new javax.swing.JButton();
        btnDialogEmpleados = new javax.swing.JButton();
        btnEmpleadosFacturacion = new javax.swing.JButton();
        btnTablaClienteCochesReparaciones = new javax.swing.JButton();

        jLabel1.setText("Codigo Cliente");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Email");

        jLabel6.setText("Telefono");

        txtCodCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodCliFocusLost(evt);
            }
        });

        txtNomCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomCliFocusLost(evt);
            }
        });

        btnAltaCli.setText("Alta Cliente");
        btnAltaCli.setEnabled(false);
        btnAltaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaCliActionPerformed(evt);
            }
        });

        btnBajaCli.setText("Baja Cliente");
        btnBajaCli.setEnabled(false);
        btnBajaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaCliActionPerformed(evt);
            }
        });

        btnModifCli.setText("Modificar");
        btnModifCli.setEnabled(false);
        btnModifCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifCliActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar Coches");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogClienteLayout = new javax.swing.GroupLayout(DialogCliente.getContentPane());
        DialogCliente.getContentPane().setLayout(DialogClienteLayout);
        DialogClienteLayout.setHorizontalGroup(
            DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogClienteLayout.createSequentialGroup()
                .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogClienteLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNomCli, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodCli))))
                    .addGroup(DialogClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAltaCli)
                        .addGap(18, 18, 18)
                        .addComponent(btnBajaCli)
                        .addGap(18, 18, 18)
                        .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrar)
                            .addComponent(btnModifCli))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogClienteLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTfno)
                            .addComponent(txtEmail)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        DialogClienteLayout.setVerticalGroup(
            DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogClienteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifCli)
                    .addComponent(btnAltaCli)
                    .addComponent(btnBajaCli))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(DialogClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogClienteLayout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtTfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        txtPropietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPropietarioFocusLost(evt);
            }
        });

        btnInsertCoche.setText("Insertar");
        btnInsertCoche.setEnabled(false);
        btnInsertCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCocheActionPerformed(evt);
            }
        });

        btnBajaCoche.setText("Baja coche");
        btnBajaCoche.setEnabled(false);
        btnBajaCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaCocheActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricula");

        jLabel7.setText("Marca");

        jLabel8.setText("Modelo");

        jLabel9.setText("Nombre Cliente");

        txtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout DialogCocheLayout = new javax.swing.GroupLayout(DialogCoche.getContentPane());
        DialogCoche.getContentPane().setLayout(DialogCocheLayout);
        DialogCocheLayout.setHorizontalGroup(
            DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogCocheLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnInsertCoche)
                .addGap(43, 43, 43)
                .addComponent(btnBajaCoche)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogCocheLayout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addGroup(DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(txtMatricula)
                        .addComponent(txtMarca)
                        .addComponent(txtModelo)
                        .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(182, Short.MAX_VALUE)))
        );
        DialogCocheLayout.setVerticalGroup(
            DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogCocheLayout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addGroup(DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBajaCoche)
                    .addComponent(btnInsertCoche))
                .addGap(59, 59, 59))
            .addGroup(DialogCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogCocheLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(4, 4, 4)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addGap(3, 3, 3)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel8)
                    .addGap(4, 4, 4)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );

        DialogReparaciones.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                DialogReparacionesWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                DialogReparacionesWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                DialogReparacionesWindowOpened(evt);
            }
        });

        jLabel11.setText("Empleado");

        jLabel12.setText("Matricula");

        jLabel13.setText("Importe");

        jLabel14.setText("Fecha Entrada");

        jLabel15.setText("Fecha Salida");

        txtRepMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepMatriculaFocusLost(evt);
            }
        });
        txtRepMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepMatriculaActionPerformed(evt);
            }
        });

        txtRepFechaEnt.setText("2025-12-01 00:00:00");
        txtRepFechaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepFechaEntActionPerformed(evt);
            }
        });

        txtRepFechaSal.setEnabled(false);
        txtRepFechaSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepFechaSalActionPerformed(evt);
            }
        });

        btnEntrada.setText("Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSalida.setText("Salida");
        btnSalida.setEnabled(false);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnComprobar.setText("Comprobar");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogReparacionesLayout = new javax.swing.GroupLayout(DialogReparaciones.getContentPane());
        DialogReparaciones.getContentPane().setLayout(DialogReparacionesLayout);
        DialogReparacionesLayout.setHorizontalGroup(
            DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogReparacionesLayout.createSequentialGroup()
                        .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DialogReparacionesLayout.createSequentialGroup()
                                .addComponent(btnEntrada)
                                .addGap(49, 49, 49)
                                .addComponent(btnSalida))
                            .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(txtRepFechaSal, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(txtRepFechaEnt)
                                .addComponent(txtImporte)))
                        .addContainerGap(151, Short.MAX_VALUE))
                    .addGroup(DialogReparacionesLayout.createSequentialGroup()
                        .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(DialogReparacionesLayout.createSequentialGroup()
                                .addComponent(txtRepMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnComprobar))
                            .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 89, Short.MAX_VALUE))))
        );
        DialogReparacionesLayout.setVerticalGroup(
            DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogReparacionesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobar))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepFechaEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepFechaSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(DialogReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada)
                    .addComponent(btnSalida))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        DialogTablaCoches.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                DialogTablaCochesWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                DialogTablaCochesWindowOpened(evt);
            }
        });

        tablaCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaCoches);

        javax.swing.GroupLayout DialogTablaCochesLayout = new javax.swing.GroupLayout(DialogTablaCoches.getContentPane());
        DialogTablaCoches.getContentPane().setLayout(DialogTablaCochesLayout);
        DialogTablaCochesLayout.setHorizontalGroup(
            DialogTablaCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaCochesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        DialogTablaCochesLayout.setVerticalGroup(
            DialogTablaCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaCochesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        DialogTablaBonificacionEmpleados.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                DialogTablaBonificacionEmpleadosWindowActivated(evt);
            }
        });

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        cbMesEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbMesEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesEmpleadosActionPerformed(evt);
            }
        });

        jLabel10.setText("Mes");

        javax.swing.GroupLayout DialogTablaBonificacionEmpleadosLayout = new javax.swing.GroupLayout(DialogTablaBonificacionEmpleados.getContentPane());
        DialogTablaBonificacionEmpleados.getContentPane().setLayout(DialogTablaBonificacionEmpleadosLayout);
        DialogTablaBonificacionEmpleadosLayout.setHorizontalGroup(
            DialogTablaBonificacionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaBonificacionEmpleadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DialogTablaBonificacionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbMesEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        DialogTablaBonificacionEmpleadosLayout.setVerticalGroup(
            DialogTablaBonificacionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogTablaBonificacionEmpleadosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cbMesEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        DialogTablaFacturacion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                DialogTablaFacturacionWindowActivated(evt);
            }
        });

        tablaFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaFacturacion);

        cbMesFacturacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbMesFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesFacturacionActionPerformed(evt);
            }
        });

        jLabel16.setText("Mes");

        javax.swing.GroupLayout DialogTablaFacturacionLayout = new javax.swing.GroupLayout(DialogTablaFacturacion.getContentPane());
        DialogTablaFacturacion.getContentPane().setLayout(DialogTablaFacturacionLayout);
        DialogTablaFacturacionLayout.setHorizontalGroup(
            DialogTablaFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaFacturacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DialogTablaFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbMesFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        DialogTablaFacturacionLayout.setVerticalGroup(
            DialogTablaFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaFacturacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(cbMesFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel17.setText("Nombre Cliente");

        txtNombreTablaClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreTablaClientesFocusLost(evt);
            }
        });

        jLabel18.setText("Numero de Coches");

        txtNumCoches.setText("0");

        tablaReparacionesCoche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaReparacionesCoche);

        btnBuscarClienteCoches.setText("Buscar");
        btnBuscarClienteCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteCochesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogTablaClienteCochesReparacionesLayout = new javax.swing.GroupLayout(DialogTablaClienteCochesReparaciones.getContentPane());
        DialogTablaClienteCochesReparaciones.getContentPane().setLayout(DialogTablaClienteCochesReparacionesLayout);
        DialogTablaClienteCochesReparacionesLayout.setHorizontalGroup(
            DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaClienteCochesReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DialogTablaClienteCochesReparacionesLayout.createSequentialGroup()
                        .addGroup(DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtNombreTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCoches)
                            .addComponent(jLabel18)))
                    .addComponent(btnBuscarClienteCoches))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        DialogTablaClienteCochesReparacionesLayout.setVerticalGroup(
            DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTablaClienteCochesReparacionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogTablaClienteCochesReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCoches))
                .addGap(21, 21, 21)
                .addComponent(btnBuscarClienteCoches)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnDialogCliente.setText("Cliente");
        btnDialogCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogClienteActionPerformed(evt);
            }
        });

        btnDialogCoches.setText("Coche");
        btnDialogCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogCochesActionPerformed(evt);
            }
        });

        btnDialogReparaciones.setText("Reparaciones");
        btnDialogReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogReparacionesActionPerformed(evt);
            }
        });

        btnDialogEmpleados.setText("Empleados Bonificaciones");
        btnDialogEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogEmpleadosActionPerformed(evt);
            }
        });

        btnEmpleadosFacturacion.setText("Empleados Facturacion");
        btnEmpleadosFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosFacturacionActionPerformed(evt);
            }
        });

        btnTablaClienteCochesReparaciones.setText("Cliente numero Reparaciones");
        btnTablaClienteCochesReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaClienteCochesReparacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTablaClienteCochesReparaciones)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDialogCliente)
                                .addGap(27, 27, 27)
                                .addComponent(btnDialogCoches))
                            .addComponent(btnDialogEmpleados))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpleadosFacturacion)
                            .addComponent(btnDialogReparaciones))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDialogCliente)
                    .addComponent(btnDialogCoches)
                    .addComponent(btnDialogReparaciones))
                .addGap(18, 18, 18)
                .addComponent(btnTablaClienteCochesReparaciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpleadosFacturacion)
                    .addComponent(btnDialogEmpleados))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaCliActionPerformed
        controladorPrincipal.insertarCliente();
    }//GEN-LAST:event_btnAltaCliActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controladorPrincipal.cerrarSession();
    }//GEN-LAST:event_formWindowClosed

    private void txtCodCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodCliFocusLost
        
    }//GEN-LAST:event_txtCodCliFocusLost

    private void btnModifCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifCliActionPerformed
        controladorPrincipal.modificarCliente();
    }//GEN-LAST:event_btnModifCliActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        DialogTablaCoches.setVisible(true);
        DialogTablaCoches.setSize(450, 600);
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnInsertCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCocheActionPerformed
        controladorPrincipal.altaCoche();
    }//GEN-LAST:event_btnInsertCocheActionPerformed

    private void btnBajaCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaCocheActionPerformed
        controladorPrincipal.bajaCoche();
    }//GEN-LAST:event_btnBajaCocheActionPerformed

    private void btnDialogClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogClienteActionPerformed
        DialogCliente.setVisible(true);
        DialogCliente.setSize(386, 489);
    }//GEN-LAST:event_btnDialogClienteActionPerformed

    private void btnDialogCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogCochesActionPerformed
       DialogCoche.setVisible(true);
       DialogCoche.setSize(386, 489);
        
    }//GEN-LAST:event_btnDialogCochesActionPerformed

    private void txtPropietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPropietarioFocusLost
        
    }//GEN-LAST:event_txtPropietarioFocusLost

    private void txtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaFocusLost
        controladorPrincipal.comprobarCoche();
    }//GEN-LAST:event_txtMatriculaFocusLost

    private void btnDialogReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogReparacionesActionPerformed
       DialogReparaciones.setVisible(true);
       DialogReparaciones.setSize(500,500);
    }//GEN-LAST:event_btnDialogReparacionesActionPerformed

    private void DialogTablaCochesWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogTablaCochesWindowOpened
       // controladorPrincipal.mostrarCoches();
    }//GEN-LAST:event_DialogTablaCochesWindowOpened

    private void DialogTablaCochesWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogTablaCochesWindowActivated
       controladorPrincipal.mostrarCoches();
    }//GEN-LAST:event_DialogTablaCochesWindowActivated

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
       
        controladorPrincipal.entradaReparacion();
         
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void txtRepFechaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepFechaSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepFechaSalActionPerformed

    private void txtRepFechaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepFechaEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepFechaEntActionPerformed

    private void txtNomCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomCliFocusLost
        controladorPrincipal.comprobarCliente();
    }//GEN-LAST:event_txtNomCliFocusLost

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        controladorPrincipal.salidaReparacion();
         
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnDialogEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogEmpleadosActionPerformed
        DialogTablaBonificacionEmpleados.setVisible(true);
       DialogTablaBonificacionEmpleados.setSize(500,500);
    }//GEN-LAST:event_btnDialogEmpleadosActionPerformed

    private void cbMesEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesEmpleadosActionPerformed
        controladorPrincipal.cargarTablaBonificaciones();
    }//GEN-LAST:event_cbMesEmpleadosActionPerformed

    private void txtRepMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepMatriculaActionPerformed
        
    }//GEN-LAST:event_txtRepMatriculaActionPerformed

    private void txtRepMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepMatriculaFocusLost
       // controladorPrincipal.comprobarReparacion();
       // System.out.println("Focus Lost en txtRepMatricula");
    }//GEN-LAST:event_txtRepMatriculaFocusLost

    private void DialogReparacionesWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogReparacionesWindowActivated
        //controladorPrincipal.llenarComboEmpleados();
    }//GEN-LAST:event_DialogReparacionesWindowActivated

    private void DialogReparacionesWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogReparacionesWindowOpened
        //controladorPrincipal.llenarComboEmpleados();
    }//GEN-LAST:event_DialogReparacionesWindowOpened

    private void DialogTablaBonificacionEmpleadosWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogTablaBonificacionEmpleadosWindowActivated
       
        //controladorPrincipal.actualizarBonificaciones();
        
    }//GEN-LAST:event_DialogTablaBonificacionEmpleadosWindowActivated

    public JTable getTablaReparacionesCoche() {
        return tablaReparacionesCoche;
    }

    public JTextField getTxtNombreTablaClientes() {
        return txtNombreTablaClientes;
    }

    public JLabel getTxtNumCoches() {
        return txtNumCoches;
    }

    private void DialogReparacionesWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogReparacionesWindowClosed
        
    }//GEN-LAST:event_DialogReparacionesWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controladorPrincipal.llenarComboEmpleados();
    }//GEN-LAST:event_formWindowOpened

    private void btnEmpleadosFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosFacturacionActionPerformed
       DialogTablaFacturacion.setVisible(true);
       DialogTablaFacturacion.setSize(500,500); 
    }//GEN-LAST:event_btnEmpleadosFacturacionActionPerformed

    private void cbMesFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesFacturacionActionPerformed
        controladorPrincipal.facturacion();
    }//GEN-LAST:event_cbMesFacturacionActionPerformed

    private void DialogTablaFacturacionWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogTablaFacturacionWindowActivated
        
    }//GEN-LAST:event_DialogTablaFacturacionWindowActivated

    private void btnTablaClienteCochesReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaClienteCochesReparacionesActionPerformed
        DialogTablaClienteCochesReparaciones.setVisible(true);
       DialogTablaClienteCochesReparaciones.setSize(500,500);
    }//GEN-LAST:event_btnTablaClienteCochesReparacionesActionPerformed

    private void txtNombreTablaClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreTablaClientesFocusLost
        
    }//GEN-LAST:event_txtNombreTablaClientesFocusLost

    private void btnBuscarClienteCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteCochesActionPerformed
        controladorPrincipal.cargarCochesReparaciones();
    }//GEN-LAST:event_btnBuscarClienteCochesActionPerformed

    private void btnBajaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaCliActionPerformed
        controladorPrincipal.bajaCliente();
    }//GEN-LAST:event_btnBajaCliActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        controladorPrincipal.comprobarReparacion();
    }//GEN-LAST:event_btnComprobarActionPerformed

    /**
     * @param args the command line arguments
     */

    public JComboBox<String> getCbMesEmpleados() {
        return cbMesEmpleados;
    }

    public JTable getTablaEmpleados() {
        return tablaEmpleados;
    }

    public JComboBox<String> getCbMesFacturacion() {
        return cbMesFacturacion;
    }

    public JTable getTablaFacturacion() {
        return tablaFacturacion;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogCliente;
    private javax.swing.JDialog DialogCoche;
    private javax.swing.JDialog DialogReparaciones;
    private javax.swing.JDialog DialogTablaBonificacionEmpleados;
    private javax.swing.JDialog DialogTablaClienteCochesReparaciones;
    private javax.swing.JDialog DialogTablaCoches;
    private javax.swing.JDialog DialogTablaFacturacion;
    private javax.swing.JButton btnAltaCli;
    private javax.swing.JButton btnBajaCli;
    private javax.swing.JButton btnBajaCoche;
    private javax.swing.JButton btnBuscarClienteCoches;
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnDialogCliente;
    private javax.swing.JButton btnDialogCoches;
    private javax.swing.JButton btnDialogEmpleados;
    private javax.swing.JButton btnDialogReparaciones;
    private javax.swing.JButton btnEmpleadosFacturacion;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnInsertCoche;
    private javax.swing.JButton btnModifCli;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnTablaClienteCochesReparaciones;
    private javax.swing.JComboBox<Empleados> cbEmpleados;
    private javax.swing.JComboBox<String> cbMesEmpleados;
    private javax.swing.JComboBox<String> cbMesFacturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaCoches;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaFacturacion;
    private javax.swing.JTable tablaReparacionesCoche;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNomCli;
    private javax.swing.JTextField txtNombreTablaClientes;
    private javax.swing.JLabel txtNumCoches;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtRepFechaEnt;
    private javax.swing.JTextField txtRepFechaSal;
    private javax.swing.JTextField txtRepMatricula;
    private javax.swing.JTextField txtTfno;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAltaCli() {
        return btnAltaCli;
    }

    public JComboBox<Empleados> getCbEmpleados() {
        return cbEmpleados;
    }

    public JButton getBtnBajaCli() {
        return btnBajaCli;
    }

    public JButton getBtnModifCli() {
        return btnModifCli;
    }

    public JTextField getTxtCodCli() {
        return txtCodCli;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtNomCli() {
        return txtNomCli;
    }

    public JTextField getTxtTfno() {
        return txtTfno;
    }

    public JButton getBtnBajaCoche() {
        return btnBajaCoche;
    }

    public JButton getBtnInsertCoche() {
        return btnInsertCoche;
    }

    public JButton getBtnMostrar() {
        return btnMostrar;
    }

    public JTable getTablaCoches() {
        return tablaCoches;
    }

   

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public JTextField getTxtPropietario() {
        return txtPropietario;
    }

    public JButton getBtnEntrada() {
        return btnEntrada;
    }

    public JButton getBtnSalida() {
        return btnSalida;
    }

    public JTextField getTxtImporte() {
        return txtImporte;
    }

    

    public JTextField getTxtRepFechaEnt() {
        return txtRepFechaEnt;
    }

    public JTextField getTxtRepFechaSal() {
        return txtRepFechaSal;
    }

    public JTextField getTxtRepMatricula() {
        return txtRepMatricula;
    }

    


}
